import type { LocalText } from "./course-data-bilingual";

export type BeginnerGuide = {
  plainTitle: LocalText;
  definition: LocalText;
  whyItMatters: LocalText;
  scenario: { title: LocalText; story: LocalText };
  flow: { label: LocalText; explanation: LocalText }[];
  workedExample: {
    title: LocalText;
    question: LocalText;
    given: LocalText[];
    steps: LocalText[];
    result: LocalText;
  };
  glossary: { term: LocalText; meaning: LocalText; example: LocalText }[];
  commonMistake: LocalText;
  actions: LocalText[];
};

const t = (es: string, en: string): LocalText => ({ es, en });

export const beginnerGuides: BeginnerGuide[] = [
  {
    plainTitle: t("Sostenibilidad: hacer bien el trabajo hoy sin crear un problema mañana", "Sustainability: doing today's job well without creating tomorrow's problem"),
    definition: t("En este curso, sostenibilidad no significa que un avión sea «verde». Significa tomar decisiones que mantengan la misión y la seguridad, pero utilizando mejor combustible, energía, agua, materiales y repuestos, y evitando trasladar el problema a otra persona, otro lugar o el futuro.", "In this course, sustainability does not mean that an aircraft is ‘green’. It means making decisions that preserve mission and safety while using fuel, energy, water, materials and spares better, without moving the problem to another person, place or time."),
    whyItMatters: t("Una pequeña decisión de ingeniería puede afectar a muchas áreas. Cambiar un equipo de tierra puede reducir diésel, pero exigir más electricidad, baterías, formación y capacidad de emergencia. Por eso se mira el conjunto antes de aprobar.", "A small engineering decision can affect many areas. Replacing a ground unit may reduce diesel but require more electricity, batteries, training and emergency capacity. That is why the whole picture is reviewed before approval."),
    scenario: { title: t("Situación de trabajo: sustituir un tractor diésel", "Work situation: replacing a diesel tug"), story: t("El equipo propone un tractor eléctrico para mover material en plataforma. Parece una mejora evidente. Sin embargo, antes de aprobar hay que comprobar autonomía en invierno, tiempo de carga, electricidad consumida, batería, equipo de reserva, seguridad y si el mismo número de tareas se completa a tiempo. La sostenibilidad aparece al comparar todos esos efectos, no al fijarse solo en el tubo de escape.", "The team proposes an electric tug for apron material handling. It looks like an obvious improvement. Before approval, however, winter range, charging time, electricity use, battery, backup equipment, safety and completion of the same number of tasks must be checked. Sustainability appears when all these effects are compared, not when only the exhaust pipe is considered.") },
    flow: [
      { label: t("Trabajo a realizar", "Required job"), explanation: t("Definir la tarea: qué se entrega, cuántas veces y con qué nivel de disponibilidad.", "Define the task: what is delivered, how often and at what availability level.") },
      { label: t("Recursos usados", "Resources used"), explanation: t("Anotar combustible, electricidad, agua, materiales, horas y transporte.", "Record fuel, electricity, water, materials, hours and transport.") },
      { label: t("Efectos creados", "Effects created"), explanation: t("Comprobar emisiones, residuos, exposición, coste y consecuencias operativas.", "Check emissions, waste, exposure, cost and operational consequences.") },
      { label: t("Decisión con límites", "Bounded decision"), explanation: t("Aprobar, pilotar o rechazar indicando las condiciones que deben mantenerse.", "Approve, pilot or reject while stating the conditions that must be maintained.") },
    ],
    workedExample: { title: t("Ejemplo sencillo: comparar dos opciones", "Simple example: compare two options"), question: t("¿Conviene sustituir el tractor diésel por uno eléctrico?", "Should the diesel tug be replaced by an electric one?"), given: [t("Diésel actual: 1.000 litros/año.", "Current diesel: 1,000 litres/year."), t("Opción eléctrica: 2.400 kWh/año y una recarga durante el turno.", "Electric option: 2,400 kWh/year and one charge during the shift."), t("Ambas opciones completan 500 tareas/año; la eléctrica necesita un plan de contingencia.", "Both options complete 500 tasks/year; the electric option needs a contingency plan.")], steps: [t("Comparar la misma función: 500 tareas completadas.", "Compare the same function: 500 completed tasks."), t("Calcular consumos y emisiones con factores declarados.", "Calculate consumption and emissions with declared factors."), t("Comprobar disponibilidad, seguridad, batería y respuesta ante fallo eléctrico.", "Check availability, safety, battery and response to power failure.")], result: t("La opción eléctrica puede pilotarse si mantiene las 500 tareas y supera la prueba de contingencia. No se afirma que sea «cero emisiones»: se informa de electricidad, batería y exclusiones.", "The electric option can be piloted if it maintains 500 tasks and passes the contingency test. It is not called ‘zero emission’: electricity, battery and exclusions are reported.") },
    glossary: [
      { term: t("Impacto ambiental", "Environmental impact"), meaning: t("Cambio causado en el entorno o en las personas.", "A change caused to the environment or people."), example: t("Emisiones, consumo de agua, ruido o generación de residuos.", "Emissions, water use, noise or waste generation.") },
      { term: t("Perímetro", "Boundary"), meaning: t("Qué procesos y etapas se incluyen en el análisis.", "Which processes and stages are included in the analysis."), example: t("Solo uso del tractor o también fabricación de batería y electricidad.", "Tug use only, or battery manufacture and electricity too.") },
      { term: t("Trade-off", "Trade-off"), meaning: t("Una mejora que trae una desventaja en otro aspecto.", "An improvement that brings a disadvantage elsewhere."), example: t("Menos diésel, pero más dependencia de la red eléctrica.", "Less diesel, but greater dependence on the electricity grid.") },
    ],
    commonMistake: t("Llamar sostenible a una opción porque mejora un único dato. Un dato favorable no demuestra que la decisión completa sea mejor.", "Calling an option sustainable because it improves one figure. One favourable figure does not prove the complete decision is better."),
    actions: [t("Definir la tarea que debe mantenerse.", "Define the task that must be preserved."), t("Comparar las alternativas con el mismo perímetro.", "Compare alternatives with the same boundary."), t("Revisar seguridad, misión, coste e impacto juntos.", "Review safety, mission, cost and impact together."), t("Escribir qué no se ha medido.", "Write down what has not been measured.")],
  },
  {
    plainTitle: t("Impacto medido y percepción: dos informaciones diferentes", "Measured impact and perception: two different kinds of information"),
    definition: t("Un sonómetro puede indicar cuánto ruido hubo, pero no explica por sí solo cómo lo vivieron las personas. La percepción depende también de la hora, la frecuencia, la sorpresa, la confianza y la posibilidad de recibir una explicación o participar en la solución.", "A sound meter can show how much noise occurred, but it does not explain by itself how people experienced it. Perception also depends on time, frequency, surprise, trust and the opportunity to receive an explanation or participate in the solution."),
    whyItMatters: t("En aeronáutica podemos demostrar técnicamente que un promedio ha bajado y, al mismo tiempo, recibir más quejas. No significa que la medición sea falsa: quizá los eventos se han concentrado por la noche, sobre un barrio o durante una actividad especialmente sensible.", "In aviation we can technically prove that an average fell and still receive more complaints. This does not mean the measurement is false: events may have become concentrated at night, over one neighbourhood or during a particularly sensitive activity."),
    scenario: { title: t("Situación de trabajo: pruebas de motor trasladadas a la tarde", "Work situation: engine tests moved to the evening"), story: t("Una nueva planificación reduce el tiempo total de pruebas y el combustible utilizado. Para conseguirlo, varias pruebas pasan de la mañana a las 20:00. El promedio mensual de ruido apenas cambia, pero veinte viviendas reciben ahora más eventos cuando están ocupadas. Para evaluar el resultado hay que medir los eventos y escuchar a los receptores, no elegir entre «datos» o «opiniones».", "A new schedule reduces total test time and fuel use. To achieve it, several tests move from the morning to 20:00. The monthly noise average barely changes, but twenty homes now receive more events while occupied. Evaluation must measure events and listen to receptors rather than choosing between ‘data’ and ‘opinions’." ) },
    flow: [
      { label: t("Cambia el horario", "Schedule changes"), explanation: t("Parte de las pruebas pasa de la mañana a la tarde-noche.", "Some tests move from the morning to the evening.") },
      { label: t("Cambia quién lo recibe", "Receptors change"), explanation: t("Más personas están en casa y escuchan cada evento.", "More people are at home and hear each event.") },
      { label: t("Medimos y escuchamos", "Measure and listen"), explanation: t("Se revisan niveles, número de eventos, horarios, quejas y entrevistas.", "Levels, event counts, times, complaints and interviews are reviewed.") },
      { label: t("Ajustamos la decisión", "Adjust the decision"), explanation: t("Se cambia el horario, se limita el número o se explica por qué no hay alternativa.", "The schedule or count is changed, or the lack of an alternative is explained.") },
    ],
    workedExample: { title: t("Ejemplo sencillo: la media no cuenta toda la historia", "Simple example: the average does not tell the whole story"), question: t("¿Ha mejorado realmente el programa de pruebas?", "Has the test programme really improved?"), given: [t("Combustible por prueba: baja un 8 %.", "Fuel per test: down 8%."), t("Promedio acústico mensual: baja 1 dB.", "Monthly noise average: down 1 dB."), t("Eventos después de las 19:00: suben de 6 a 18; quejas: de 3 a 14.", "Events after 19:00: up from 6 to 18; complaints: from 3 to 14.")], steps: [t("Separar los resultados: combustible, promedio acústico y distribución horaria.", "Separate fuel, average noise and time distribution results."), t("Localizar quién recibe los 12 eventos nocturnos adicionales.", "Identify who receives the 12 additional evening events."), t("Comprobar si el canal de quejas y la población han cambiado.", "Check whether the complaint channel and population changed.")], result: t("Hay una mejora de combustible, pero no una mejora ambiental completa. La recomendación debe mantener el ahorro y corregir o justificar los eventos vespertinos.", "There is a fuel improvement, but not a complete environmental improvement. The recommendation must preserve the saving and correct or justify the evening events.") },
    glossary: [
      { term: t("Exposición", "Exposure"), meaning: t("Cantidad de ruido, contaminante u otro efecto que llega a una persona o lugar.", "Amount of noise, pollutant or other effect reaching a person or place."), example: t("Dieciocho eventos acústicos en una vivienda entre las 19:00 y las 22:00.", "Eighteen noise events at a home between 19:00 and 22:00." ) },
      { term: t("Receptor", "Receptor"), meaning: t("Persona, edificio, hábitat o zona que recibe el efecto.", "Person, building, habitat or area receiving the effect."), example: t("Trabajadores de plataforma o viviendas próximas.", "Apron workers or nearby homes." ) },
      { term: t("Percepción", "Perception"), meaning: t("Cómo interpreta y vive una persona el impacto.", "How a person interprets and experiences the impact."), example: t("Sentir pérdida de control ante pruebas inesperadas.", "Feeling a loss of control when tests are unexpected." ) },
    ],
    commonMistake: t("Responder a una preocupación social con un único promedio técnico. El promedio puede ser correcto y seguir ocultando cuándo, dónde y a quién afecta.", "Answering a social concern with one technical average. The average may be correct and still hide when, where and who is affected."),
    actions: [t("Separar nivel, frecuencia, horario y distribución.", "Separate level, frequency, timing and distribution."), t("Identificar receptores antes de cambiar una operación.", "Identify receptors before changing an operation."), t("Combinar medición y escucha estructurada.", "Combine measurement and structured listening."), t("Responder a compromisos con fecha y responsable.", "Respond to commitments with a date and owner." )],
  },
  {
    plainTitle: t("Huella ambiental: seguir los consumos desde el origen hasta el final", "Environmental footprint: follow consumption from origin to end"),
    definition: t("Una huella ambiental es un inventario ordenado de lo que entra y sale para prestar un servicio: materiales, energía, transporte, emisiones y residuos. El análisis de ciclo de vida, o ACV, amplía la mirada desde la fabricación hasta el uso, el mantenimiento y el fin de vida.", "An environmental footprint is an organised inventory of what enters and leaves to provide a service: materials, energy, transport, emissions and waste. Life cycle assessment, or LCA, broadens the view from manufacturing through use, maintenance and end of life."),
    whyItMatters: t("Sin esta visión, una reparación local puede parecer peor porque consume electricidad en nuestro centro, aunque evite fabricar una pieza nueva y transportarla. También puede ocurrir lo contrario: reparar repetidamente una pieza con poca vida remanente puede generar más carga que sustituirla.", "Without this view, a local repair can appear worse because it uses electricity at our site, even though it avoids manufacturing and transporting a new part. The opposite can also happen: repeatedly repairing a part with little remaining life may create more burden than replacement."),
    scenario: { title: t("Situación de trabajo: reparar o sustituir una válvula", "Work situation: repair or replace a valve"), story: t("La reparación utiliza limpieza, disolvente, electricidad y un ensayo. La sustitución necesita una válvula nueva, embalaje y transporte. Para comparar no se suman datos al azar: se define primero el mismo resultado, por ejemplo «una válvula apta para servicio durante 12 meses».", "Repair uses cleaning, solvent, electricity and a test. Replacement needs a new valve, packaging and transport. To compare them, data are not added at random: the same result is defined first, for example ‘one serviceable valve for 12 months’." ) },
    flow: [
      { label: t("Definir la función", "Define the function"), explanation: t("Comparar opciones que entregan el mismo servicio y duración.", "Compare options delivering the same service and duration." ) },
      { label: t("Dibujar etapas", "Map stages"), explanation: t("Fabricación, transporte, uso, mantenimiento y fin de vida.", "Manufacturing, transport, use, maintenance and end of life." ) },
      { label: t("Recoger datos", "Collect data"), explanation: t("Masa, energía, kilómetros, rendimiento, vida y residuos.", "Mass, energy, kilometres, yield, life and waste." ) },
      { label: t("Comparar y probar", "Compare and test"), explanation: t("Ver qué supuesto podría cambiar la opción preferida.", "See which assumption could change the preferred option." ) },
    ],
    workedExample: { title: t("Ejemplo sencillo: reparación frente a pieza nueva", "Simple example: repair versus new part"), question: t("¿Qué opción entrega un año de función con menor carga?", "Which option delivers one year of function with less burden?"), given: [t("Reparación: 12 kWh, 0,5 l de disolvente y 20 km; vida esperada: 12 meses.", "Repair: 12 kWh, 0.5 L solvent and 20 km; expected life: 12 months."), t("Pieza nueva: 4 kg de material, fabricación y 800 km; vida esperada: 48 meses.", "New part: 4 kg material, manufacturing and 800 km; expected life: 48 months."), t("Se comparará por 12 meses de función, no por una unidad física.", "Comparison is per 12 months of function, not per physical item." )], steps: [t("Dividir la carga de la pieza nueva entre los años de vida previstos cuando el método lo permita.", "Allocate the new part burden across expected life where the method allows."), t("Añadir consumos y transporte de cada ruta.", "Add consumption and transport for each route."), t("Probar qué pasa si la reparación dura solo seis meses.", "Test what happens if the repair lasts only six months." )], result: t("La reparación se recomienda únicamente si la vida validada supera el umbral. El dato crítico no es el kWh: es la vida remanente real.", "Repair is recommended only if validated life exceeds the threshold. The critical data point is not kWh: it is actual remaining life." ) },
    glossary: [
      { term: t("ACV", "LCA"), meaning: t("Método para estudiar impactos a lo largo del ciclo de vida.", "Method for studying impacts across the lifecycle."), example: t("De materia prima a fabricación, uso, mantenimiento y retirada.", "From raw material to manufacture, use, maintenance and retirement." ) },
      { term: t("Unidad funcional", "Functional unit"), meaning: t("Servicio común que permite comparar alternativas.", "Common service that allows alternatives to be compared."), example: t("Una válvula apta durante 12 meses.", "One serviceable valve for 12 months." ) },
      { term: t("Hotspot", "Hotspot"), meaning: t("Etapa que aporta una parte importante del impacto.", "Stage contributing a significant share of impact."), example: t("Fabricación del material o combustible durante el uso.", "Material manufacture or fuel during use." ) },
    ],
    commonMistake: t("Comparar una reparación con una pieza nueva sin igualar la función ni la duración. El resultado parecerá preciso, pero estará comparando cosas distintas.", "Comparing a repair with a new part without matching function and duration. The result will look precise while comparing different things."),
    actions: [t("Escribir la pregunta de decisión.", "Write the decision question."), t("Definir una unidad funcional comprensible.", "Define an understandable functional unit."), t("Dibujar qué etapas entran y salen.", "Map included and excluded stages."), t("Probar el supuesto que más cambia el resultado.", "Test the assumption that changes the result most." )],
  },
  {
    plainTitle: t("Cambio climático: no es solo contar el CO₂ del combustible", "Climate change: more than counting fuel CO₂"),
    definition: t("El CO₂ liberado al quemar combustible se acumula durante mucho tiempo y calienta el clima. La aviación también altera la atmósfera mediante NOx, vapor, partículas y algunas estelas persistentes. Estos efectos no CO₂ dependen mucho de la altura y de la meteorología y se estudian por separado.", "CO₂ released by fuel combustion accumulates for a long time and warms the climate. Aviation also changes the atmosphere through NOx, water vapour, particles and some persistent contrails. These non-CO₂ effects depend strongly on altitude and weather and are studied separately."),
    whyItMatters: t("Reducir combustible suele reducir CO₂, pero una decisión de trayectoria puede cambiar las estelas, el tiempo de vuelo y el ruido. No existe una conversión sencilla que sirva para todas las decisiones; hay que explicar qué efectos se han calculado y cuáles no.", "Reducing fuel generally reduces CO₂, but a route decision can change contrails, flight time and noise. There is no simple conversion suitable for every decision; calculated and uncalculated effects must be stated."),
    scenario: { title: t("Situación de trabajo: subir o bajar para evitar una estela", "Work situation: climb or descend to avoid a contrail"), story: t("La previsión indica una zona fría y húmeda donde podría formarse una estela persistente. Cambiar 2.000 pies quizá la evite, pero añade combustible y requiere una trayectoria autorizada. El ensayo debe registrar el CO₂ adicional y la respuesta prevista de la estela, además de la misión y el espacio aéreo.", "The forecast indicates a cold humid region where a persistent contrail may form. A 2,000-foot change might avoid it but adds fuel and requires an authorised trajectory. The trial must record added CO₂ and predicted contrail response, as well as mission and airspace effects." ) },
    flow: [
      { label: t("Vuelo y combustible", "Flight and fuel"), explanation: t("La cantidad quemada determina el CO₂ directo.", "Burned fuel determines direct CO₂." ) },
      { label: t("Altura y atmósfera", "Altitude and atmosphere"), explanation: t("Meteorología y emisiones determinan posibles efectos no CO₂.", "Weather and emissions determine possible non-CO₂ effects." ) },
      { label: t("Dos resultados", "Two results"), explanation: t("CO₂ y no CO₂ se muestran separados, con su incertidumbre.", "CO₂ and non-CO₂ are shown separately with uncertainty." ) },
      { label: t("Decisión prudente", "Cautious decision"), explanation: t("Se prueba solo donde la previsión y las condiciones operativas son adecuadas.", "Trial only where forecasts and operational conditions are suitable." ) },
    ],
    workedExample: { title: t("Ejemplo sencillo: CO₂ directo", "Simple example: direct CO₂"), question: t("¿Cuánto CO₂ directo se evita al ahorrar combustible?", "How much direct CO₂ is avoided by saving fuel?"), given: [t("Ahorro verificado: 300 kg de combustible por misión.", "Verified saving: 300 kg fuel per mission."), t("Misiones comparables: 50 al año.", "Comparable missions: 50 per year."), t("Factor ilustrativo de combustión: 3,16 kg CO₂ por kg de combustible.", "Illustrative combustion factor: 3.16 kg CO₂ per kg fuel." )], steps: [t("Combustible anual evitado: 300 × 50 = 15.000 kg.", "Annual avoided fuel: 300 × 50 = 15,000 kg."), t("CO₂ directo: 15.000 × 3,16 = 47.400 kg.", "Direct CO₂: 15,000 × 3.16 = 47,400 kg."), t("Declarar que no incluye producción del combustible ni efectos no CO₂.", "State that fuel production and non-CO₂ effects are excluded." )], result: t("Resultado defendible: 47,4 t de CO₂ directo evitadas para las 50 misiones definidas. No se denomina «impacto climático total».", "Defensible result: 47.4 t direct CO₂ avoided for the 50 defined missions. It is not called ‘total climate impact’." ) },
    glossary: [
      { term: t("CO₂ directo", "Direct CO₂"), meaning: t("CO₂ generado al quemar combustible durante la operación.", "CO₂ generated by burning fuel during operation."), example: t("Combustión en motores principales o APU.", "Combustion in main engines or APU." ) },
      { term: t("Efectos no CO₂", "Non-CO₂ effects"), meaning: t("Cambios climáticos causados por otras emisiones y procesos atmosféricos.", "Climate changes caused by other emissions and atmospheric processes."), example: t("NOx y estelas persistentes.", "NOx and persistent contrails." ) },
      { term: t("Ciclo de vida del combustible", "Fuel lifecycle"), meaning: t("Producción y transporte anteriores a su uso.", "Production and transport before use."), example: t("Extracción, refino, producción de SAF y distribución.", "Extraction, refining, SAF production and distribution." ) },
    ],
    commonMistake: t("Multiplicar combustible por un factor de CO₂ y presentar el resultado como impacto climático total. Ese cálculo solo representa una parte bien definida.", "Multiplying fuel by a CO₂ factor and presenting the result as total climate impact. That calculation represents only one defined part."),
    actions: [t("Separar CO₂, ciclo de vida y no CO₂.", "Separate CO₂, lifecycle and non-CO₂."), t("Indicar el horizonte y la fuente del factor.", "State the horizon and factor source."), t("Comprobar penalizaciones operativas.", "Check operational penalties."), t("Usar pilotos reversibles cuando hay incertidumbre.", "Use reversible trials where uncertainty exists." )],
  },
  {
    plainTitle: t("Eficiencia energética: hacer la misma misión con menos energía", "Energy efficiency: deliver the same mission with less energy"),
    definition: t("Eficiencia energética significa obtener el mismo resultado útil utilizando menos energía. En una aeronave intervienen masa, resistencia, motor, trayectoria y configuración; en tierra, equipos, edificios, electricidad y tiempos de funcionamiento.", "Energy efficiency means obtaining the same useful result with less energy. In an aircraft, mass, drag, engine, route and configuration matter; on the ground, equipment, buildings, electricity and operating time matter."),
    whyItMatters: t("Decir que una misión consumió menos no demuestra una mejora si llevaba menos carga, tuvo viento favorable o terminó una tarea diferente. La comparación debe corregir esas diferencias antes de atribuir el ahorro a una medida.", "Saying that a mission used less fuel does not prove an improvement if it carried less payload, had favourable wind or completed a different task. Those differences must be corrected before attributing the saving to a measure."),
    scenario: { title: t("Situación de trabajo: nueva regla de planificación de combustible", "Work situation: new fuel-planning rule"), story: t("Después de cinco vuelos aparece un ahorro medio de 450 kg. Al revisar los datos, tres vuelos tenían menos carga y viento de cola. El equipo selecciona misiones comparables y el ahorro atribuible baja a 150 kg. Esta segunda cifra es menor, pero es la que puede defenderse.", "After five flights an average saving of 450 kg appears. Data review shows that three flights had less payload and tailwind. The team selects comparable missions and attributable saving falls to 150 kg. This second figure is smaller, but it is the defensible one." ) },
    flow: [
      { label: t("Misma misión", "Same mission"), explanation: t("Igualar carga, distancia, configuración, reservas y resultado.", "Match payload, distance, configuration, reserves and outcome." ) },
      { label: t("Medir consumo", "Measure consumption"), explanation: t("Usar combustible o energía realmente consumidos.", "Use actual consumed fuel or energy." ) },
      { label: t("Separar influencias", "Separate influences"), explanation: t("Revisar viento, temperatura, esperas, desvíos y estado técnico.", "Review wind, temperature, holding, diversions and technical condition." ) },
      { label: t("Escalar con control", "Scale with control"), explanation: t("Aplicar solo a misiones donde el ahorro y la seguridad se mantienen.", "Apply only to missions where saving and safety are maintained." ) },
    ],
    workedExample: { title: t("Ejemplo sencillo: ahorro anual", "Simple example: annual saving"), question: t("¿Qué ahorro anual puede declararse?", "What annual saving can be claimed?"), given: [t("Ahorro normalizado: entre 120 y 180 kg por misión elegible.", "Normalised saving: 120–180 kg per eligible mission."), t("Misiones elegibles: 80 al año.", "Eligible missions: 80 per year."), t("Las misiones con desvíos frecuentes quedan fuera.", "Diversion-heavy missions are excluded." )], steps: [t("Límite inferior: 120 × 80 = 9.600 kg.", "Lower bound: 120 × 80 = 9,600 kg."), t("Límite superior: 180 × 80 = 14.400 kg.", "Upper bound: 180 × 80 = 14,400 kg."), t("Mantener reservas, disponibilidad y registro de excepciones.", "Maintain reserves, availability and exception records." )], result: t("Se declara un rango de 9,6–14,4 t de combustible al año, no una cifra falsa de precisión. El rango solo aplica a la población definida.", "A range of 9.6–14.4 t fuel per year is reported, not a falsely precise figure. The range applies only to the defined population." ) },
    glossary: [
      { term: t("Línea base", "Baseline"), meaning: t("Situación de referencia contra la que se compara.", "Reference situation used for comparison."), example: t("Consumo de misiones equivalentes antes del cambio.", "Consumption of equivalent missions before the change." ) },
      { term: t("Normalizar", "Normalise"), meaning: t("Corregir diferencias que no proceden de la medida.", "Adjust differences not caused by the measure."), example: t("Carga, viento, distancia o temperatura.", "Payload, wind, distance or temperature." ) },
      { term: t("Rebote", "Rebound"), meaning: t("El ahorro por tarea se pierde porque aumenta la actividad total.", "Per-task saving is lost because total activity increases."), example: t("Menos combustible por misión, pero muchas más misiones.", "Less fuel per mission, but many more missions." ) },
    ],
    commonMistake: t("Comparar dos vuelos diferentes y atribuir toda la diferencia a un procedimiento. Sin misiones equivalentes no hay evidencia del ahorro.", "Comparing two different flights and attributing the entire difference to a procedure. Without equivalent missions there is no saving evidence."),
    actions: [t("Definir la población elegible.", "Define the eligible population."), t("Normalizar carga, meteo y configuración.", "Normalise payload, weather and configuration."), t("Informar un rango cuando los datos varían.", "Report a range when data vary."), t("Vigilar seguridad, demora y disponibilidad.", "Monitor safety, delay and availability." )],
  },
  {
    plainTitle: t("Calidad del aire: saber qué respiran las personas y de dónde procede", "Air quality: understand what people breathe and where it comes from"),
    definition: t("La calidad del aire describe la concentración de contaminantes en un lugar y momento determinados. No es lo mismo que emisiones: una fuente puede emitir una cantidad, pero el viento, la distancia y otras fuentes determinan cuánto llega finalmente a un trabajador o a una vivienda.", "Air quality describes pollutant concentration at a particular place and time. It is not the same as emissions: a source may emit an amount, but wind, distance and other sources determine how much finally reaches a worker or home."),
    whyItMatters: t("En una base se combinan motores, APU, vehículos, equipos de tierra, calefacción y contaminación regional. Para actuar bien hay que conectar una fuente concreta con un receptor concreto y evitar atribuir automáticamente todo el valor medido a la actividad aeronáutica.", "At a base, engines, APU, vehicles, ground equipment, heating and regional pollution combine. Good action connects a specific source to a specific receptor and avoids automatically attributing every measured value to aviation activity."),
    scenario: { title: t("Situación de trabajo: olor y NO₂ durante una prueba", "Work situation: odour and NO₂ during a test"), story: t("Los trabajadores de una zona a sotavento notifican molestias durante pruebas de motor. Un medidor central de la base no muestra un problema claro porque promedia todo el día. Se instala un equipo móvil a sotavento y otro a barlovento, y se sincronizan los datos con la hora de cada prueba y la dirección del viento.", "Workers in a downwind area report discomfort during engine tests. A central base monitor shows no clear problem because it averages the whole day. A mobile instrument is installed downwind and another upwind, and data are synchronised with each test time and wind direction." ) },
    flow: [
      { label: t("Fuente", "Source"), explanation: t("Identificar motor, APU, vehículo o proceso y su horario.", "Identify engine, APU, vehicle or process and its timing." ) },
      { label: t("Viento y dispersión", "Wind and dispersion"), explanation: t("Comprobar hacia dónde se mueve y diluye el contaminante.", "Check where the pollutant moves and dilutes." ) },
      { label: t("Receptor", "Receptor"), explanation: t("Localizar personas o zonas ocupadas durante el evento.", "Locate people or occupied areas during the event." ) },
      { label: t("Control", "Control"), explanation: t("Cambiar fuente, horario, ubicación o protección y volver a medir.", "Change source, time, location or protection and measure again." ) },
    ],
    workedExample: { title: t("Ejemplo sencillo: separar fondo y contribución local", "Simple example: separate background and local contribution"), question: t("¿La prueba está contribuyendo al pico observado?", "Is the test contributing to the observed peak?"), given: [t("Punto a barlovento: 28 µg/m³ de NO₂.", "Upwind point: 28 µg/m³ NO₂."), t("Punto a sotavento durante la prueba: 72 µg/m³.", "Downwind point during test: 72 µg/m³."), t("Sin prueba y con viento similar: 31 µg/m³ a sotavento.", "Without a test and in similar wind: 31 µg/m³ downwind." )], steps: [t("Comparar el mismo intervalo temporal y condiciones de viento.", "Compare the same time interval and wind conditions."), t("Usar barlovento como indicación del fondo entrante.", "Use upwind as an indication of incoming background."), t("Repetir varios eventos antes de atribuir causalidad.", "Repeat across several events before attributing causality." )], result: t("Los datos sugieren una contribución local durante la prueba, pero un solo evento no basta. Se propone un ensayo de horario o ubicación y seguimiento repetido.", "Data suggest a local contribution during the test, but one event is insufficient. A time or location trial and repeated monitoring are proposed." ) },
    glossary: [
      { term: t("Emisión", "Emission"), meaning: t("Cantidad de contaminante liberada por una fuente.", "Amount of pollutant released by a source."), example: t("NOx emitido durante una prueba de motor.", "NOx emitted during an engine test." ) },
      { term: t("Concentración", "Concentration"), meaning: t("Cantidad de contaminante presente en un volumen de aire.", "Amount of pollutant in a volume of air."), example: t("µg/m³ de NO₂ en un puesto de trabajo.", "µg/m³ NO₂ at a workplace." ) },
      { term: t("Barlovento / sotavento", "Upwind / downwind"), meaning: t("Antes y después de la fuente según la dirección del viento.", "Before and after the source according to wind direction."), example: t("Un monitor de fondo y otro donde llega el penacho.", "One background monitor and another where the plume arrives." ) },
    ],
    commonMistake: t("Usar el consumo total de combustible como si indicara directamente lo que respira una persona. Entre emisión y exposición intervienen lugar, tiempo y meteorología.", "Using total fuel consumption as if it directly indicated what a person breathes. Place, time and weather intervene between emission and exposure."),
    actions: [t("Relacionar medición con actividad y viento.", "Link measurement to activity and wind."), t("Medir fondo y receptor.", "Measure background and receptor."), t("Usar periodos adecuados al evento.", "Use averaging periods suitable for the event."), t("Verificar el control con nueva medición.", "Verify the control through new measurement." )],
  },
  {
    plainTitle: t("Ruido: no solo importa cuánto, también cuándo, cuántas veces y a quién", "Noise: amount matters, but so do time, frequency and receptor"),
    definition: t("El ruido aeronáutico se describe con medidas físicas, pero la molestia depende también del número de eventos, la hora y el lugar. Un valor medio resume energía sonora; no sustituye el análisis de picos ni de eventos nocturnos.", "Aircraft noise is described with physical measurements, but annoyance also depends on the number of events, time and place. An average value summarises sound energy; it does not replace analysis of peaks or night events."),
    whyItMatters: t("Una modificación de ruta, una zona de pruebas o una secuencia de motor puede reducir el promedio de muchas personas y aumentar mucho la carga sobre unas pocas. La decisión debe mostrar esa distribución.", "A route change, test area or engine sequence may reduce the average for many people while greatly increasing the burden on a few. The decision must show that distribution."),
    scenario: { title: t("Situación de trabajo: mover el área de pruebas", "Work situation: moving the test area"), story: t("La nueva ubicación queda más lejos de las viviendas, pero más cerca de un taller ocupado. El modelo predice una mejora comunitaria. Antes de convertirla en permanente se miden ambos receptores, el remolque necesario, la meteorología y la validez de la prueba.", "The new location is farther from homes but closer to an occupied workshop. The model predicts a community improvement. Before making it permanent, both receptors, required towing, weather and test validity are measured." ) },
    flow: [
      { label: t("Fuente sonora", "Sound source"), explanation: t("Tipo de aeronave, potencia, configuración y duración.", "Aircraft type, power, configuration and duration." ) },
      { label: t("Propagación", "Propagation"), explanation: t("Distancia, viento, terreno, edificios y reflexiones.", "Distance, wind, terrain, buildings and reflections." ) },
      { label: t("Personas expuestas", "People exposed"), explanation: t("Viviendas, talleres y horarios de ocupación.", "Homes, workshops and occupancy periods." ) },
      { label: t("Combinación de medidas", "Combination of measures"), explanation: t("Fuente, ubicación, procedimiento, horario y restricciones.", "Source, location, procedure, timing and restrictions." ) },
    ],
    workedExample: { title: t("Ejemplo sencillo: media y eventos", "Simple example: average and events"), question: t("¿Cuál de las dos alternativas es claramente mejor?", "Which alternative is clearly better?"), given: [t("Opción A: 55 dB de promedio y 4 eventos nocturnos de 78 dB.", "Option A: 55 dB average and four 78 dB night events."), t("Opción B: 56 dB de promedio y ningún evento nocturno; más exposición en horario laboral.", "Option B: 56 dB average and no night events; more exposure during working hours."), t("Ambas cumplen las barreras técnicas del ensayo.", "Both meet technical test gates." )], steps: [t("No sumar ni promediar métricas que representan cosas distintas.", "Do not add or average metrics representing different things."), t("Identificar población y horario afectados en cada opción.", "Identify affected population and timing for each option."), t("Consultar a operación y prevención antes del piloto.", "Consult operations and occupational safety before the trial." )], result: t("No hay un ganador automático. Se pilota la opción B si la exposición laboral puede controlarse; la decisión conserva ambos indicadores.", "There is no automatic winner. Option B is piloted if worker exposure can be controlled; the decision retains both indicators." ) },
    glossary: [
      { term: t("dB", "dB"), meaning: t("Unidad logarítmica del nivel sonoro; una diferencia numérica no se interpreta como una escala lineal.", "Logarithmic sound-level unit; a numerical difference is not interpreted as a linear scale."), example: t("No se suman 60 dB + 60 dB como 120 dB.", "60 dB + 60 dB is not 120 dB." ) },
      { term: t("LAeq", "LAeq"), meaning: t("Nivel continuo equivalente durante un periodo.", "Equivalent continuous level over a period."), example: t("Promedio energético de una jornada.", "Energy average across a day." ) },
      { term: t("SEL", "SEL"), meaning: t("Energía acústica de un evento individual normalizada en el tiempo.", "Sound energy of one event normalised in time."), example: t("Comparar dos pruebas de distinta duración.", "Compare two tests of different duration." ) },
    ],
    commonMistake: t("Decir que bajar un promedio resuelve el ruido. Puede dejar intactos los picos, la noche o la concentración sobre un receptor.", "Saying that lowering an average solves noise. Peaks, night events or concentration over one receptor may remain."),
    actions: [t("Definir fuente, receptor y horario.", "Define source, receptor and time."), t("Conservar métricas de promedio y evento.", "Retain average and event metrics."), t("Evaluar efectos desplazados.", "Assess displaced effects."), t("Probar medidas con meteorología representativa.", "Trial measures in representative weather." )],
  },
  {
    plainTitle: t("Agua y residuos: controlar el proceso antes de contar el contenedor", "Water and waste: control the process before counting the bin"),
    definition: t("Gestionar agua y residuos significa saber dónde se consumen recursos, dónde se contaminan y qué ocurre con cada corriente hasta su destino final. La prioridad es evitar generar el residuo; separar y reciclar vienen después.", "Managing water and waste means knowing where resources are consumed, where they become contaminated and what happens to each stream through final destination. Avoiding waste comes first; separation and recycling follow."),
    whyItMatters: t("Dos talleres pueden producir la misma masa de residuo y tener desempeños muy distintos: uno evitó derrames y segregó bien; el otro mezcló un residuo recuperable con uno peligroso y obligó a gestionar todo como peligroso.", "Two workshops may produce the same waste mass and have very different performance: one prevented spills and segregated correctly; the other mixed recoverable waste with hazardous waste and forced all of it into hazardous management."),
    scenario: { title: t("Situación de trabajo: lavado de componentes", "Work situation: component washing"), story: t("El proceso utiliza agua y detergente. El equipo quiere reutilizar el último aclarado como primer lavado del siguiente lote. Antes del cambio se comprueba calidad del agua, compatibilidad, corrosión, consumo por lote y carga contaminante del vertido.", "The process uses water and detergent. The team wants to reuse the final rinse as the first wash for the next batch. Before the change, water quality, compatibility, corrosion, batch consumption and discharge pollutant load are checked." ) },
    flow: [
      { label: t("Compra y entrada", "Purchase and input"), explanation: t("Agua, productos, envases y piezas que entran al proceso.", "Water, products, packaging and parts entering the process." ) },
      { label: t("Uso en la tarea", "Use in the task"), explanation: t("Dónde, cuánto y por qué se consume o contamina.", "Where, how much and why it is consumed or contaminated." ) },
      { label: t("Separación y control", "Separation and control"), explanation: t("Evitar mezclas, derrames y pérdida de valor.", "Avoid mixing, spills and loss of value." ) },
      { label: t("Destino comprobado", "Verified destination"), explanation: t("Conservar analíticas, documentos y gestor final.", "Retain analyses, documents and final contractor." ) },
    ],
    workedExample: { title: t("Ejemplo sencillo: consumo por tarea", "Simple example: consumption per task"), question: t("¿La medida reduce realmente el consumo de agua?", "Does the measure really reduce water consumption?"), given: [t("Antes: 1.200 m³ para 600 lotes.", "Before: 1,200 m³ for 600 batches."), t("Después: 1.050 m³ para 750 lotes.", "After: 1,050 m³ for 750 batches."), t("La calidad y el vertido siguen dentro de criterios.", "Quality and discharge remain within criteria." )], steps: [t("Antes: 1.200 / 600 = 2,0 m³ por lote.", "Before: 1,200 / 600 = 2.0 m³ per batch."), t("Después: 1.050 / 750 = 1,4 m³ por lote.", "After: 1,050 / 750 = 1.4 m³ per batch."), t("Mostrar también el total, que baja 150 m³ pese al aumento de actividad.", "Also show the total, which falls by 150 m³ despite increased activity." )], result: t("La medida reduce tanto intensidad como consumo absoluto. Se mantiene si calidad, corrosión y vertido no empeoran.", "The measure reduces both intensity and absolute use. It is retained if quality, corrosion and discharge do not worsen." ) },
    glossary: [
      { term: t("Prevención", "Prevention"), meaning: t("Evitar que el residuo o consumo se produzca.", "Avoid creating the waste or consumption."), example: t("Dosificación automática que evita producto sobrante.", "Automatic dosing that avoids leftover product." ) },
      { term: t("Segregación", "Segregation"), meaning: t("Separar corrientes sin mezclarlas.", "Keep streams separate without mixing."), example: t("Trapos contaminados separados de papel limpio.", "Contaminated wipes separated from clean paper." ) },
      { term: t("Carga contaminante", "Pollutant load"), meaning: t("Cantidad total de contaminante, no solo su concentración.", "Total amount of pollutant, not only concentration."), example: t("Concentración multiplicada por volumen vertido.", "Concentration multiplied by discharged volume." ) },
    ],
    commonMistake: t("Celebrar una tasa de reciclaje alta sin comprobar cuánto residuo total se generó ni adónde llegó realmente.", "Celebrating a high recycling rate without checking total waste generation or where it actually went."),
    actions: [t("Medir por proceso o tarea.", "Measure by process or task."), t("Aplicar prevención antes que reciclaje.", "Apply prevention before recycling."), t("Segregar en el punto de generación.", "Segregate at the point of generation."), t("Verificar analíticas y destino final.", "Verify analyses and final destination." )],
  },
  {
    plainTitle: t("Biodiversidad y fauna: proteger el entorno sin aumentar el riesgo operacional", "Biodiversity and wildlife: protect nature without increasing operational risk"),
    definition: t("Biodiversidad es la variedad de seres vivos, hábitats y relaciones que existen en un lugar. En un aeródromo debe gestionarse junto con el riesgo de fauna: algunas mejoras de hábitat pueden atraer especies hacia zonas incompatibles con la operación.", "Biodiversity is the variety of living organisms, habitats and relationships in a place. At an aerodrome it must be managed together with wildlife risk: some habitat improvements may attract species towards areas incompatible with operations."),
    whyItMatters: t("No se trata de eliminar toda la fauna ni de crear naturaleza en cualquier espacio disponible. Se trata de conocer especies, movimientos y atractores, conservar donde sea compatible y reducir el riesgo donde la misión lo exige.", "The aim is neither to remove all wildlife nor to create nature in every available space. It is to understand species, movements and attractants, conserve where compatible and reduce risk where mission requires it."),
    scenario: { title: t("Situación de trabajo: una balsa que atrae aves", "Work situation: a pond attracting birds"), story: t("Una zona de drenaje mantiene agua después de lluvias y atrae aves de gran tamaño cerca de la trayectoria. Antes de vaciarla o vallarla se identifica la especie, horarios, motivo de atracción y función hidráulica. La solución puede ser cambiar pendiente, vegetación o tiempo de permanencia del agua, no destruir indiscriminadamente el hábitat.", "A drainage area retains water after rain and attracts large birds near the flight path. Before draining or fencing it, species, timing, attractant and hydraulic function are identified. The solution may be to change slope, vegetation or water-retention time rather than indiscriminately destroy habitat." ) },
    flow: [
      { label: t("Observar especies", "Observe species"), explanation: t("Quién aparece, cuántos, cuándo y con qué comportamiento.", "Who appears, how many, when and with what behaviour." ) },
      { label: t("Encontrar el atractor", "Find the attractant"), explanation: t("Agua, alimento, refugio, vegetación o residuos.", "Water, food, shelter, vegetation or waste." ) },
      { label: t("Evaluar riesgo", "Assess risk"), explanation: t("Cruzar especie, masa, número, ubicación y fase de vuelo.", "Combine species, mass, number, location and flight phase." ) },
      { label: t("Actuar y observar", "Act and observe"), explanation: t("Modificar hábitat y comprobar si aparece otro problema.", "Modify habitat and check whether another problem appears." ) },
    ],
    workedExample: { title: t("Ejemplo sencillo: contar no es evaluar", "Simple example: counting is not assessing"), question: t("¿Qué zona presenta mayor riesgo?", "Which area presents greater risk?"), given: [t("Zona A: 40 aves pequeñas lejos de pista.", "Zone A: 40 small birds far from runway."), t("Zona B: 4 aves grandes cruzando aproximación al amanecer.", "Zone B: four large birds crossing approach at dawn."), t("Zona C: 12 aves medianas en área sin operaciones.", "Zone C: 12 medium birds in a non-operational area." )], steps: [t("No ordenar únicamente por número de aves.", "Do not rank only by bird count."), t("Considerar masa, comportamiento, ubicación y coincidencia temporal.", "Consider mass, behaviour, location and time overlap."), t("Priorizar el escenario con mayor consecuencia y probabilidad de encuentro.", "Prioritise the scenario with greatest consequence and encounter likelihood." )], result: t("La Zona B puede requerir prioridad aunque tenga menos aves. La decisión se documenta por riesgo, no por impresión visual.", "Zone B may require priority despite fewer birds. The decision is documented by risk, not visual impression." ) },
    glossary: [
      { term: t("Atractor", "Attractant"), meaning: t("Elemento que hace que una especie use un lugar.", "Feature causing a species to use a place."), example: t("Agua estancada, alimento o refugio.", "Standing water, food or shelter." ) },
      { term: t("Hábitat", "Habitat"), meaning: t("Lugar y condiciones que necesita una especie.", "Place and conditions required by a species."), example: t("Pradera, cubierta, humedal o edificio.", "Grassland, roof, wetland or building." ) },
      { term: t("Riesgo de fauna", "Wildlife risk"), meaning: t("Combinación de probabilidad de encuentro y gravedad.", "Combination of encounter likelihood and severity."), example: t("Ave grande cruzando una fase crítica de vuelo.", "Large bird crossing a critical flight phase." ) },
    ],
    commonMistake: t("Usar «más biodiversidad» como objetivo automático dentro del área operacional. La ubicación y las especies importan tanto como la cantidad.", "Using ‘more biodiversity’ as an automatic goal within the operational area. Location and species matter as much as quantity."),
    actions: [t("Inventariar hábitats y especies.", "Inventory habitats and species."), t("Relacionar observaciones con operaciones.", "Link observations to operations."), t("Gestionar atractores por especie.", "Manage attractants by species."), t("Revisar efectos después de cada cambio.", "Review effects after every change." )],
  },
  {
    plainTitle: t("Gestión ambiental en MRO: convertir requisitos en controles de tarea", "Environmental management in MRO: turn requirements into task controls"),
    definition: t("Un sistema de gestión ambiental organiza quién identifica los impactos, qué requisitos se aplican, cómo se controla el trabajo, qué se registra y cómo se corrigen fallos. No es una carpeta de procedimientos: debe funcionar en el taller y durante un despliegue.", "An environmental management system organises who identifies impacts, which requirements apply, how work is controlled, what is recorded and how failures are corrected. It is not a folder of procedures: it must work in the workshop and during deployment."),
    whyItMatters: t("Una misma tarea puede usar disolventes, generar residuo peligroso y tener riesgo de derrame. En la base principal existen almacén, extracción y gestor; en despliegue quizá dependemos de infraestructura anfitriona. El control debe adaptarse sin perder el mínimo aceptable.", "One task may use solvents, generate hazardous waste and create spill risk. At the main base there is storage, extraction and a contractor; on deployment we may depend on host infrastructure. Control must adapt without losing the acceptable minimum."),
    scenario: { title: t("Situación de trabajo: reparación con disolvente en despliegue", "Work situation: solvent repair during deployment"), story: t("La tarea está aprobada, pero el emplazamiento anfitrión no dispone del contenedor ni de la extracción habituales. Antes de empezar se verifica sustituto autorizado, ventilación, almacenamiento temporal, kit de derrames, responsable y ruta de retirada. Si falta una barrera crítica, la tarea se detiene o escala.", "The task is approved, but the host site lacks the usual container and extraction. Before starting, authorised substitute, ventilation, temporary storage, spill kit, owner and removal route are checked. If a critical barrier is missing, the task stops or escalates." ) },
    flow: [
      { label: t("Tarea", "Task"), explanation: t("Describir lo que realmente se hace, dónde y con qué productos.", "Describe what is actually done, where and with which products." ) },
      { label: t("Aspectos y requisitos", "Aspects and requirements"), explanation: t("Identificar consumos, emisiones, residuos, riesgos y obligaciones.", "Identify consumption, emissions, waste, risks and obligations." ) },
      { label: t("Controles", "Controls"), explanation: t("Definir equipos, instrucciones, competencias y respuesta.", "Define equipment, instructions, competence and response." ) },
      { label: t("Evidencia y mejora", "Evidence and improvement"), explanation: t("Inspeccionar, registrar, corregir causa y comprobar eficacia.", "Inspect, record, correct the cause and check effectiveness." ) },
    ],
    workedExample: { title: t("Ejemplo sencillo: comprobar una barrera", "Simple example: check a barrier"), question: t("¿Está controlado el almacenamiento temporal?", "Is temporary storage controlled?"), given: [t("Requisito interno: recipiente compatible, cerrado, etiquetado y sobre contención.", "Internal requirement: compatible, closed, labelled container on secondary containment."), t("Inspección: recipiente y etiqueta correctos; cubeto lleno de agua de lluvia.", "Inspection: correct container and label; bund full of rainwater."), t("La capacidad de contención ya no está disponible.", "Containment capacity is no longer available." )], steps: [t("No marcar el control como conforme solo porque existe el cubeto.", "Do not mark the control conforming merely because the bund exists."), t("Vaciar de forma autorizada y proteger de lluvia.", "Empty it through an authorised route and protect it from rain."), t("Registrar causa, responsable y verificación posterior.", "Record cause, owner and later verification." )], result: t("La barrera estaba instalada pero no operativa. La eficacia se demuestra después de corregir y volver a inspeccionar.", "The barrier was installed but not operational. Effectiveness is demonstrated after correction and reinspection." ) },
    glossary: [
      { term: t("Aspecto ambiental", "Environmental aspect"), meaning: t("Parte de una actividad que puede interactuar con el entorno.", "Part of an activity that can interact with the environment."), example: t("Uso de disolvente o almacenamiento de combustible.", "Solvent use or fuel storage." ) },
      { term: t("Control operacional", "Operational control"), meaning: t("Medida concreta que mantiene una tarea dentro de condiciones aceptables.", "Specific measure keeping a task within acceptable conditions."), example: t("Extracción, cubeto, instrucción o autorización.", "Extraction, bund, instruction or authorisation." ) },
      { term: t("No conformidad", "Nonconformity"), meaning: t("Incumplimiento de un requisito definido.", "Failure to meet a defined requirement."), example: t("Residuo sin etiqueta exigida.", "Waste missing the required label." ) },
    ],
    commonMistake: t("Comprobar que existe un procedimiento y dar por controlada la tarea. La auditoría debe observar si la barrera funciona donde se ejecuta el trabajo.", "Checking that a procedure exists and assuming the task is controlled. Audit must observe whether the barrier works where work is performed."),
    actions: [t("Mapear aspectos por tarea.", "Map aspects by task."), t("Definir controles mínimos de despliegue.", "Define minimum deployment controls."), t("Comprobar competencia y estado de barreras.", "Check competence and barrier condition."), t("Cerrar acciones solo tras verificar eficacia.", "Close actions only after verifying effectiveness." )],
  },
  {
    plainTitle: t("Mantenimiento sostenible: conservar disponibilidad usando mejor piezas, horas y energía", "Sustainable maintenance: preserve availability while using parts, hours and energy better"),
    definition: t("El mantenimiento sostenible no consiste en hacer menos mantenimiento. Consiste en realizar la intervención correcta, en el momento correcto y con evidencia suficiente, manteniendo aeronavegabilidad y fiabilidad mientras se evitan tareas, desmontajes, residuos o transportes sin valor.", "Sustainable maintenance does not mean performing less maintenance. It means carrying out the right intervention at the right time with sufficient evidence, preserving airworthiness and reliability while avoiding tasks, removals, waste or transport that add no value."),
    whyItMatters: t("Una inspección frecuente puede prevenir deterioro, pero también consumir piezas, horas y materiales. Un modelo predictivo puede reducir inspecciones, pero una falsa alarma provoca un desmontaje innecesario y una alerta perdida puede afectar seguridad. El beneficio se mide junto con fiabilidad y disponibilidad.", "Frequent inspection may prevent deterioration but also consume parts, hours and materials. A predictive model may reduce inspections, but a false alarm causes unnecessary removal and a missed alert may affect safety. Benefit is measured alongside reliability and availability."),
    scenario: { title: t("Situación de trabajo: mantenimiento predictivo de un componente", "Work situation: predictive maintenance for a component"), story: t("Un algoritmo anticipa degradación a partir de sensores. Durante la primera fase funciona en sombra: genera alertas, pero se mantienen las inspecciones aprobadas. Se compara cada alerta con el hallazgo real antes de permitir que el modelo cambie una tarea.", "An algorithm anticipates deterioration from sensors. In the first phase it runs in shadow mode: it generates alerts while approved inspections remain. Each alert is compared with the actual finding before the model is allowed to change a task." ) },
    flow: [
      { label: t("Señal técnica", "Technical signal"), explanation: t("Dato de sensor, tendencia o síntoma observado.", "Sensor data, trend or observed symptom." ) },
      { label: t("Decisión de mantenimiento", "Maintenance decision"), explanation: t("Inspeccionar, intervenir, observar o mantener programa.", "Inspect, intervene, monitor or retain programme." ) },
      { label: t("Hallazgo real", "Actual finding"), explanation: t("Confirmar degradación, falsa alarma o fallo no detectado.", "Confirm deterioration, false alarm or missed failure." ) },
      { label: t("Aprendizaje de flota", "Fleet learning"), explanation: t("Actualizar umbral solo para la población validada.", "Update threshold only for the validated population." ) },
    ],
    workedExample: { title: t("Ejemplo sencillo: una alerta no es un fallo", "Simple example: an alert is not a failure"), question: t("¿Está listo el modelo para sustituir una inspección?", "Is the model ready to replace an inspection?"), given: [t("100 alertas analizadas.", "100 alerts analysed."), t("60 degradaciones confirmadas; 40 desmontajes sin hallazgo.", "60 confirmed deteriorations; 40 removals with no finding."), t("Dos degradaciones aparecieron sin alerta.", "Two deteriorations appeared without an alert." )], steps: [t("Calcular falsas alertas y fallos no detectados.", "Calculate false alerts and missed detections."), t("Revisar consecuencias de los dos fallos no detectados.", "Review consequences of the two missed detections."), t("Comparar horas, logística, fiabilidad y disponibilidad.", "Compare hours, logistics, reliability and availability." )], result: t("El modelo puede seguir en sombra o en un piloto limitado, pero no sustituir automáticamente la inspección hasta superar el criterio aprobado.", "The model can continue in shadow mode or a limited pilot, but it cannot automatically replace inspection until it passes the approved criterion." ) },
    glossary: [
      { term: t("Mantenimiento por condición", "Condition-based maintenance"), meaning: t("Intervenir según el estado observado, no solo por calendario.", "Intervene according to observed condition, not only a calendar."), example: t("Tendencia de vibración que activa una inspección.", "Vibration trend triggering an inspection." ) },
      { term: t("No-fault-found", "No-fault-found"), meaning: t("Se desmonta o prueba un elemento sin confirmar el fallo esperado.", "An item is removed or tested without confirming the expected fault."), example: t("Alerta que genera logística y trabajo sin hallazgo.", "Alert generating logistics and work without a finding." ) },
      { term: t("Población validada", "Validated population"), meaning: t("Configuraciones y condiciones donde la evidencia aplica.", "Configurations and conditions to which evidence applies."), example: t("Un estándar de software y rango de temperatura concretos.", "A specific software standard and temperature range." ) },
    ],
    commonMistake: t("Contar inspecciones evitadas como beneficio sin restar falsas alarmas, desmontajes, logística y posibles efectos sobre fiabilidad.", "Counting avoided inspections as benefit without subtracting false alarms, removals, logistics and possible reliability effects."),
    actions: [t("Mantener barreras aprobadas durante el piloto.", "Retain approved gates during the pilot."), t("Vincular alerta con hallazgo real.", "Link alert to actual finding."), t("Medir fiabilidad, disponibilidad y recursos.", "Measure reliability, availability and resources."), t("Escalar solo en configuración validada.", "Scale only in validated configuration." )],
  },
  {
    plainTitle: t("Circularidad en MRO: conservar el valor antes de convertirlo en residuo", "Circularity in MRO: preserve value before turning it into waste"),
    definition: t("La economía circular intenta mantener piezas, equipos y materiales en uso con el mayor valor posible. En MRO la prioridad suele ser mantener, reparar, actualizar o reutilizar con trazabilidad; recuperar material es una opción posterior y eliminar es la última.", "The circular economy seeks to keep parts, equipment and materials in use at the highest possible value. In MRO, keeping, repairing, upgrading or reusing with traceability usually comes first; material recovery follows and disposal is last."),
    whyItMatters: t("Reciclar aluminio recupera material, pero reparar un equipo puede conservar fabricación, mecanizado y función. Sin embargo, extender vida no siempre gana: puede mantener alto consumo, exigir inspecciones crecientes o depender de repuestos obsoletos.", "Recycling aluminium recovers material, but repairing equipment can preserve manufacture, machining and function. Life extension does not always win: it may retain high consumption, require increasing inspections or depend on obsolete spares."),
    scenario: { title: t("Situación de trabajo: extender o sustituir un equipo de apoyo", "Work situation: extend or replace support equipment"), story: t("Veinte equipos siguen siendo reparables, pero consumen más energía que el modelo nuevo. Sustituir todos a la vez genera fabricación, formación y repuestos varados. Se compara una transición escalonada: extender los equipos en mejor estado mientras se pilota la nueva tecnología.", "Twenty units remain repairable but use more energy than the new model. Replacing all at once creates manufacture, training and stranded spares. A phased transition is compared: extend the best-condition units while piloting the new technology." ) },
    flow: [
      { label: t("Mantener", "Keep"), explanation: t("Usar mientras cumple función, seguridad y rendimiento aceptable.", "Use while function, safety and acceptable performance are maintained." ) },
      { label: t("Reparar o actualizar", "Repair or upgrade"), explanation: t("Recuperar función o mejorar sin sustituir todo el activo.", "Restore or improve function without replacing the whole asset." ) },
      { label: t("Reutilizar", "Reuse"), explanation: t("Transferir pieza o equipo con estado y trazabilidad válidos.", "Transfer part or equipment with valid condition and traceability." ) },
      { label: t("Recuperar material", "Recover material"), explanation: t("Separar materiales cuando ya no puede conservarse la función.", "Separate materials when function can no longer be preserved." ) },
    ],
    workedExample: { title: t("Ejemplo sencillo: transición escalonada", "Simple example: phased transition"), question: t("¿Cuándo conviene sustituir?", "When should replacement occur?"), given: [t("Equipo actual: 10 años de edad y reparable tres años más.", "Current equipment: 10 years old and repairable for three more years."), t("Nuevo equipo: 25 % menos energía por tarea.", "New equipment: 25% less energy per task."), t("Cambio inmediato exige formación, herramienta y dos años de soporte paralelo.", "Immediate change requires training, tooling and two years of parallel support." )], steps: [t("Comparar mantener tres años, sustituir ahora y transición por lotes.", "Compare keeping for three years, replacing now and batch transition."), t("Incluir energía, fiabilidad, reparaciones, fabricación y soporte paralelo.", "Include energy, reliability, repairs, manufacture and parallel support."), t("Definir umbral de fiabilidad u obsolescencia que activa retirada.", "Define reliability or obsolescence threshold triggering retirement." )], result: t("La transición por lotes puede evitar sustitución prematura y controlar aprendizaje. La decisión se revisa anualmente con fiabilidad y consumo real.", "Batch transition may avoid premature replacement and control learning. The decision is reviewed annually using actual reliability and consumption." ) },
    glossary: [
      { term: t("Extensión de vida", "Life extension"), meaning: t("Mantener un activo en servicio más tiempo de forma aprobada.", "Keep an asset in service longer through an approved route."), example: t("Inspección y reparación que validan tres años adicionales.", "Inspection and repair validating three additional years." ) },
      { term: t("Valor retenido", "Retained value"), meaning: t("Función, trabajo y material que no se pierden.", "Function, work and material that are not lost."), example: t("Reutilizar un componente apto en lugar de fundirlo.", "Reuse a serviceable component rather than melt it." ) },
      { term: t("Obsolescencia", "Obsolescence"), meaning: t("Pérdida de soporte, piezas, herramienta o conocimiento.", "Loss of support, parts, tools or knowledge."), example: t("Equipo reparable pero sin repuesto electrónico disponible.", "Repairable equipment without available electronic spare." ) },
    ],
    commonMistake: t("Usar el porcentaje reciclado como único indicador de circularidad. Reciclar puede recuperar menos valor que mantener o reparar.", "Using recycling percentage as the only circularity indicator. Recycling may recover less value than keeping or repairing."),
    actions: [t("Aplicar la jerarquía de valor.", "Apply the value hierarchy."), t("Comprobar condición y trazabilidad.", "Check condition and traceability."), t("Incluir la carga de transición.", "Include transition burden."), t("Definir un criterio claro de salida.", "Define a clear exit criterion." )],
  },
  {
    plainTitle: t("Fin de vida: retirar una aeronave sin perder control, trazabilidad ni materiales", "End of life: retire an aircraft without losing control, traceability or materials"),
    definition: t("El fin de vida comienza antes del desmontaje. Incluye decidir la retirada, asegurar información y equipos, eliminar fluidos y sustancias peligrosas, recuperar piezas autorizadas, separar materiales y demostrar el destino final.", "End of life begins before dismantling. It includes deciding retirement, securing information and equipment, removing fluids and hazardous substances, recovering authorised parts, separating materials and demonstrating final destination."),
    whyItMatters: t("Una aeronave retirada sigue teniendo riesgos, información, componentes valiosos y responsabilidad ambiental. Venderla a un gestor no transfiere automáticamente todas las obligaciones ni demuestra qué se reutilizó, recicló o eliminó.", "A retired aircraft still contains risks, information, valuable components and environmental liability. Selling it to a contractor does not automatically transfer every obligation or prove what was reused, recycled or disposed."),
    scenario: { title: t("Situación de trabajo: seleccionar la ruta de retirada", "Work situation: select the retirement route"), story: t("Se estudian almacenamiento, extracción de piezas y desmantelamiento completo. Antes de elegir se revisan propiedad, configuración, equipos sensibles, fluidos, piezas con trazabilidad, contaminación, mercado y capacidad real del contratista.", "Storage, part-out and full dismantling are considered. Before choosing, ownership, configuration, sensitive equipment, fluids, traceable parts, contamination, markets and actual contractor capability are reviewed." ) },
    flow: [
      { label: t("Decidir y asegurar", "Decide and secure"), explanation: t("Autoridad de retirada, propiedad, configuración y seguridad.", "Retirement authority, ownership, configuration and security." ) },
      { label: t("Descontaminar", "Depollute"), explanation: t("Retirar combustibles, aceites, baterías y sustancias peligrosas.", "Remove fuel, oils, batteries and hazardous substances." ) },
      { label: t("Recuperar con trazabilidad", "Recover with traceability"), explanation: t("Liberar piezas solo cuando estado y documentación lo permiten.", "Release parts only where condition and documentation allow." ) },
      { label: t("Conciliar y cerrar", "Reconcile and close"), explanation: t("Balance de masas, destinos, certificados y emplazamiento.", "Mass balance, destinations, certificates and site." ) },
    ],
    workedExample: { title: t("Ejemplo sencillo: comprobar una afirmación de reciclaje", "Simple example: check a recycling claim"), question: t("¿Puede aceptarse «95 % recuperado»?", "Can ‘95% recovered’ be accepted?"), given: [t("Masa de entrada: 60 t.", "Input mass: 60 t."), t("Piezas reutilizadas: 8 t; materiales reciclados con certificado: 42 t.", "Reused parts: 8 t; materials recycled with certificates: 42 t."), t("Residuos eliminados: 5 t; destino no documentado: 5 t.", "Disposed waste: 5 t; undocumented destination: 5 t." )], steps: [t("Masa con destino de recuperación verificado: 8 + 42 = 50 t.", "Mass with verified recovery destination: 8 + 42 = 50 t."), t("50 / 60 = 83,3 %, no 95 %.", "50 / 60 = 83.3%, not 95%."), t("Mantener 5 t como no verificadas hasta obtener evidencia.", "Keep 5 t as unverified until evidence is obtained." )], result: t("Solo puede declararse 83,3 % de recuperación verificada dentro del perímetro definido. La masa no documentada se informa por separado.", "Only 83.3% verified recovery can be claimed within the defined boundary. Undocumented mass is reported separately." ) },
    glossary: [
      { term: t("Descontaminación", "Depollution"), meaning: t("Retirada controlada de fluidos y materiales peligrosos.", "Controlled removal of fluids and hazardous materials."), example: t("Combustible, aceite, baterías o agentes extintores.", "Fuel, oil, batteries or extinguishing agents." ) },
      { term: t("Cadena de custodia", "Chain of custody"), meaning: t("Registro de quién posee y mueve cada elemento.", "Record of who holds and moves each item."), example: t("Del emplazamiento al gestor y a la instalación final.", "From site to contractor and final facility." ) },
      { term: t("Balance de masas", "Mass balance"), meaning: t("Conciliación entre masa de entrada y todos los destinos.", "Reconciliation between input mass and all destinations."), example: t("Reutilizado + reciclado + eliminado + almacenado = entrada.", "Reused + recycled + disposed + stored = input." ) },
    ],
    commonMistake: t("Aceptar un porcentaje del contratista sin comprobar qué incluye, qué destinos están certificados y si toda la masa está conciliada.", "Accepting a contractor percentage without checking what it includes, which destinations are certified and whether all mass is reconciled."),
    actions: [t("Planificar antes de la retirada.", "Plan before retirement."), t("Caracterizar peligros y seguridad.", "Characterise hazards and security."), t("Exigir trazabilidad de piezas y destinos.", "Require traceability of parts and destinations."), t("Cerrar con balance de masas.", "Close with a mass balance." )],
  },
  {
    plainTitle: t("Riesgos mayores: evitar que un fallo pequeño se convierta en una consecuencia grave", "Major risks: prevent a small failure becoming a major consequence"),
    definition: t("Un riesgo mayor combina un suceso poco frecuente con consecuencias potencialmente graves: derrame importante, incendio, liberación, fallo de contención o interrupción crítica. Se controla mediante varias barreras independientes, no confiando en una sola medida.", "A major risk combines an infrequent event with potentially severe consequences: major spill, fire, release, loss of containment or critical interruption. It is controlled through several independent barriers rather than relying on one measure."),
    whyItMatters: t("Que un accidente no haya ocurrido recientemente no demuestra que el riesgo sea bajo. Las barreras pueden degradarse silenciosamente: un sensor fuera de servicio, un cubeto ocupado, un plan no ensayado o dos sistemas que dependen de la misma alimentación.", "The absence of a recent accident does not prove low risk. Barriers can degrade silently: an unavailable sensor, an occupied bund, an untested plan or two systems depending on the same power supply."),
    scenario: { title: t("Situación de trabajo: calor y pérdida de suministro", "Work situation: heat and supply loss"), story: t("Una ola de calor acelera la degradación de un producto aprobado mientras el proveedor anuncia una semana de demora. Usar un sustituto no autorizado puede afectar proceso y seguridad. El equipo activa stock protegido, priorización de trabajos, alternativa aprobada y criterio de escalado.", "A heat wave accelerates degradation of an approved product while the supplier announces a one-week delay. Using an unauthorised substitute may affect process and safety. The team activates protected stock, work prioritisation, approved alternative and escalation criteria." ) },
    flow: [
      { label: t("Amenaza", "Threat"), explanation: t("Causa que puede iniciar el problema.", "Cause that may initiate the problem." ) },
      { label: t("Barreras preventivas", "Preventive barriers"), explanation: t("Medidas que evitan que ocurra el evento central.", "Measures preventing the top event." ) },
      { label: t("Evento y consecuencias", "Event and consequences"), explanation: t("Qué se pierde y a quién puede afectar.", "What is lost and who may be affected." ) },
      { label: t("Mitigación y recuperación", "Mitigation and recovery"), explanation: t("Limitar daño, mantener continuidad y aprender.", "Limit damage, maintain continuity and learn." ) },
    ],
    workedExample: { title: t("Ejemplo sencillo: barreras que comparten un fallo", "Simple example: barriers sharing one failure"), question: t("¿Hay realmente dos barreras independientes?", "Are there really two independent barriers?"), given: [t("Barrera 1: sensor eléctrico de nivel alto.", "Barrier 1: electrical high-level sensor."), t("Barrera 2: bomba automática de trasiego.", "Barrier 2: automatic transfer pump."), t("Ambas dependen del mismo cuadro eléctrico sin respaldo.", "Both depend on the same electrical panel without backup." )], steps: [t("Identificar la pérdida de alimentación como causa común.", "Identify loss of power as a common cause."), t("Comprobar qué barrera queda si falla el cuadro.", "Check which barrier remains if the panel fails."), t("Añadir una capa independiente o respuesta manual probada.", "Add an independent layer or tested manual response." )], result: t("No deben contarse como dos barreras plenamente independientes. El escenario residual se evalúa con la dependencia declarada.", "They must not be counted as two fully independent barriers. Residual risk is assessed with the dependency declared." ) },
    glossary: [
      { term: t("Peligro", "Hazard"), meaning: t("Fuente con capacidad de causar daño.", "Source with potential to cause harm."), example: t("Combustible almacenado o sustancia corrosiva.", "Stored fuel or corrosive substance." ) },
      { term: t("Barrera", "Barrier"), meaning: t("Medida que previene o limita una consecuencia.", "Measure preventing or limiting a consequence."), example: t("Contención, alarma, procedimiento o equipo de respuesta.", "Containment, alarm, procedure or response equipment." ) },
      { term: t("Riesgo residual", "Residual risk"), meaning: t("Riesgo que permanece después de aplicar controles.", "Risk remaining after controls are applied."), example: t("Escenario aceptado por tiempo limitado y autoridad definida.", "Scenario accepted for a limited time by a defined authority." ) },
    ],
    commonMistake: t("Dar el riesgo por controlado porque hay varias barreras dibujadas. Hay que comprobar estado, independencia, responsable y evidencia de funcionamiento.", "Assuming risk is controlled because several barriers are drawn. Condition, independence, owner and evidence of operation must be checked."),
    actions: [t("Definir escenario y receptores.", "Define scenario and receptors."), t("Asignar dueño a cada barrera.", "Assign an owner to each barrier."), t("Probar fallos y causas comunes.", "Test failures and common causes."), t("Establecer autoridad y umbral de escalado.", "Set authority and escalation threshold." )],
  },
  {
    plainTitle: t("Reporting y responsabilidad: poder demostrar cada afirmación", "Reporting and responsibility: be able to prove every claim"),
    definition: t("Un informe de sostenibilidad explica impactos, riesgos, acciones y resultados con datos que pueden reconstruirse. Responsabilidad corporativa significa que existen propietarios, controles y decisiones detrás de las palabras, no solo una comunicación atractiva.", "A sustainability report explains impacts, risks, actions and results with data that can be reconstructed. Corporate responsibility means owners, controls and decisions sit behind the words, not only attractive communication."),
    whyItMatters: t("Una frase como «hemos mejorado un 18 %» no sirve si mezcla centros, cambia el perímetro o utiliza denominadores diferentes. La transparencia no consiste en publicar todo: consiste en definir bien, mostrar límites y proteger la información sensible sin fabricar una conclusión.", "A statement such as ‘we improved by 18%’ is meaningless if it mixes sites, changes the boundary or uses different denominators. Transparency does not mean publishing everything: it means defining clearly, showing limits and protecting sensitive information without manufacturing a conclusion."),
    scenario: { title: t("Situación de trabajo: revisar una afirmación antes de publicar", "Work situation: review a claim before publication"), story: t("El borrador afirma que «los impactos In-Service bajaron un 18 %». Al rastrear la cifra se descubre que combina electricidad verificada, una estimación de residuos y un piloto de combustible extrapolado a toda la flota. El comité separa los indicadores y limita cada frase a su evidencia real.", "The draft states that ‘In-Service impacts fell by 18%’. Tracing the figure reveals that it combines verified electricity, a waste estimate and a fuel pilot extrapolated to the whole fleet. The committee separates the indicators and limits each statement to its actual evidence." ) },
    flow: [
      { label: t("Afirmación", "Claim"), explanation: t("Escribir exactamente qué se quiere comunicar.", "Write exactly what is to be communicated." ) },
      { label: t("Dato y cálculo", "Data and calculation"), explanation: t("Rastrear fuente, fórmula, perímetro, año y responsable.", "Trace source, formula, boundary, year and owner." ) },
      { label: t("Revisión crítica", "Critical review"), explanation: t("Buscar omisiones, cambios, doble conteo y extrapolaciones.", "Look for omissions, changes, double counting and extrapolation." ) },
      { label: t("Redacción limitada", "Bounded wording"), explanation: t("Publicar resultado, alcance, periodo y limitaciones.", "Publish result, scope, period and limitations." ) },
    ],
    workedExample: { title: t("Ejemplo sencillo: porcentaje sin denominador", "Simple example: percentage without a denominator"), question: t("¿Puede publicarse «reducción del 20 %»?", "Can ‘20% reduction’ be published?"), given: [t("2025: 100 t de residuo para 1.000 órdenes.", "2025: 100 t waste for 1,000 work orders."), t("2026: 90 t para 700 órdenes.", "2026: 90 t for 700 work orders."), t("El total baja 10 %, pero por orden sube de 100 a 129 kg.", "The total falls 10%, but per order rises from 100 to 129 kg." )], steps: [t("Calcular total e intensidad.", "Calculate total and intensity."), t("Investigar el cambio de actividad y mezcla de órdenes.", "Investigate activity and work-order mix changes."), t("No escoger solo el indicador favorable.", "Do not select only the favourable indicator." )], result: t("La redacción debe explicar que bajó el residuo total con menor actividad, mientras aumentó el residuo por orden. Hace falta analizar la causa antes de atribuir mejora.", "The wording must explain that total waste fell with lower activity while waste per order rose. Cause analysis is needed before claiming improvement." ) },
    glossary: [
      { term: t("KPI", "KPI"), meaning: t("Indicador definido para seguir desempeño o avance.", "Defined indicator used to track performance or progress."), example: t("kg de residuo peligroso por orden completada.", "kg hazardous waste per completed work order." ) },
      { term: t("Trazabilidad", "Traceability"), meaning: t("Capacidad de ir desde la cifra publicada hasta el registro original.", "Ability to move from a published number to the original record."), example: t("Informe → cálculo → extracción → contador o documento.", "Report → calculation → extract → meter or document." ) },
      { term: t("Greenwashing", "Greenwashing"), meaning: t("Comunicación que exagera o presenta de forma engañosa el desempeño ambiental.", "Communication that exaggerates or misleadingly presents environmental performance."), example: t("Llamar «cero impacto» a un piloto con emisiones no incluidas.", "Calling a pilot ‘zero impact’ when emissions are excluded." ) },
    ],
    commonMistake: t("Combinar indicadores diferentes para crear una única mejora global o extrapolar un piloto a toda la organización.", "Combining different indicators into one global improvement or extrapolating a pilot to the entire organisation."),
    actions: [t("Definir cada KPI antes de calcular.", "Define every KPI before calculation."), t("Conservar fuente, fórmula y propietario.", "Retain source, formula and owner."), t("Mostrar total, intensidad y cambios de perímetro.", "Show total, intensity and boundary changes."), t("Revisar cada afirmación contra greenwashing.", "Review every claim against greenwashing." )],
  },
];
